### ISSUE TITLE
Unable to download theme in obsidian

### ISSUE THREAD

**Issue by aspatzier** [lucas-fern/obsidian-deeper-work-theme#1]
Hi, I love(d) the Deep theme in obsidian, which now is not maintained any more. Today I found your theme and wanted to try it - but it fails to download.
Any idea why installation within obsidian fails?

**Comment by lucas-fern** [comment]
Not sure sorry, it certainly works for me and other users. 

If it doesn't work after restarting Obsidian or your device you could always install it manually by taking the `obsidian.css` file from this repo and putting it in `<your vault>/.obsidian/themes`

You can rename the CSS file there and then it should show up with your other installed themes

**Comment by aspatzier** [comment]
Thanks for your hint to manually install the theme. It works. Great theme, thanks very much for sharing it!

However, installing the theme using obsidian still doesn’t work, neither on my Mac nor on the iPad. Therefore the issue still remains from my point of view

**Comment by lucas-fern** [comment]
Interesting, yeah I just tried it for myself and actually the issue exits for me too. I'll reopen this and see if I can figure out how to fix it.

**Comment by lucas-fern** [comment]
Alright, I think I've fixed this in the current release. I can now install it from the theme browser within the app and I think it should work for you as well.

**Comment by aspatzier** [comment]
Thanks for trying to fix. Just checked and it works on iPad, but not on Mac. The theme does download according to obsidian notification, but cannot be activated.
